OBJS:=formatos_3d.tex
CC:=pdflatex

test:
#	pdflatex formatos_3d.tex
	$(CC) $(OBJS)
	$(CC) $(OBJS)
	$(CC) $(OBJS)
#	evince formatos_3d.pdf

clean:
	rm -r *.log *.aux *.pdf *.gz *.toc *.out *.lof *.blg *.bbl

